apiVersion: dbrestore.local.com/v1alpha1
kind: MySQLRestore
metadata:
  labels:
    app.kubernetes.io/name: mysqlrestore
    app.kubernetes.io/managed-by: kustomize
  name: mysqlrestore-sample
spec:
  dbSpec:
    dbHost: "mysqltest"
    dbPort: "3306"
    dbName: "test1"
    dbAuth: "sqlsecret"
  s3Spec:
    endpoint: "http://192.168.100.110:9000"
    bucket: "sqldumerfile"
    s3Auth: "s3secret"
    restoreVid: "latest"
  restoreModeSpec:
    #restoreMode: "SourceTargetMode"
    # sourceTargetModeSpec:
    #   bakDBName: "mysqltest"
    restoreMode: "NewTargetMode"
    newTargetModeSpec:
      dbSpec:
        dbHost: "destmysqltest"
        dbPort: "3306"
        dbName: "test1"
        dbAuth: "destsqlsecret"
