apiVersion: dbrestore.local.com/v1alpha1
kind: MySQLRestore
metadata:
  labels:
    app.kubernetes.io/name: mysqlrestore
    app.kubernetes.io/managed-by: kustomize
  name: mysqlrestore-sample
spec:
  dbSpec:
    dbHost: "mysqltest"
    dbPort: "3306"
    dbName: "test1"
    dbAuth: "sqlsecret"
  s3Spec:
    endpoint: "http://192.168.100.110:9000"
    path: "sqldumerfile/default/528ec90b-0fa0-42f6-af48-3b96e1a0c616/mysqltest:3306/test1/2025-10-18T17:32:54Z.zst"
    s3Auth: "s3secrets"
  restoreModeSpec:
    #restoreMode: "SourceTargetMode"
    # sourceTargetModeSpec:
    #   bakDBName: "mysqltest"
    restoreMode: "NewTargetMode"
    newTargetModeSpec:
      dbSpec:
        dbHost: "destmysqltest"
        dbPort: "3306"
        dbName: "test1"
        dbAuth: "destsqlsecret"
