//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DbSpec) DeepCopyInto(out *DbSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DbSpec.
func (in *DbSpec) DeepCopy() *DbSpec {
	if in == nil {
		return nil
	}
	out := new(DbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastRestoreSpec) DeepCopyInto(out *LastRestoreSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastRestoreSpec.
func (in *LastRestoreSpec) DeepCopy() *LastRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(LastRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLRestore) DeepCopyInto(out *MySQLRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLRestore.
func (in *MySQLRestore) DeepCopy() *MySQLRestore {
	if in == nil {
		return nil
	}
	out := new(MySQLRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MySQLRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLRestoreList) DeepCopyInto(out *MySQLRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MySQLRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLRestoreList.
func (in *MySQLRestoreList) DeepCopy() *MySQLRestoreList {
	if in == nil {
		return nil
	}
	out := new(MySQLRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MySQLRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLRestoreSpec) DeepCopyInto(out *MySQLRestoreSpec) {
	*out = *in
	out.DbSpec = in.DbSpec
	out.S3Spec = in.S3Spec
	in.ResotreModeSpec.DeepCopyInto(&out.ResotreModeSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLRestoreSpec.
func (in *MySQLRestoreSpec) DeepCopy() *MySQLRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLRestoreStatus) DeepCopyInto(out *MySQLRestoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.LastRestoreSpec = in.LastRestoreSpec
	in.LastStartTime.DeepCopyInto(&out.LastStartTime)
	in.LastSucceedTime.DeepCopyInto(&out.LastSucceedTime)
	in.LastFailedTime.DeepCopyInto(&out.LastFailedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLRestoreStatus.
func (in *MySQLRestoreStatus) DeepCopy() *MySQLRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(MySQLRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NewTargetModeSpec) DeepCopyInto(out *NewTargetModeSpec) {
	*out = *in
	out.DbSpec = in.DbSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewTargetModeSpec.
func (in *NewTargetModeSpec) DeepCopy() *NewTargetModeSpec {
	if in == nil {
		return nil
	}
	out := new(NewTargetModeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreModeSpec) DeepCopyInto(out *RestoreModeSpec) {
	*out = *in
	if in.NewTargetModeSpec != nil {
		in, out := &in.NewTargetModeSpec, &out.NewTargetModeSpec
		*out = new(NewTargetModeSpec)
		**out = **in
	}
	if in.SourceTargetModeSpec != nil {
		in, out := &in.SourceTargetModeSpec, &out.SourceTargetModeSpec
		*out = new(SourceTargetModeSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreModeSpec.
func (in *RestoreModeSpec) DeepCopy() *RestoreModeSpec {
	if in == nil {
		return nil
	}
	out := new(RestoreModeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Spec) DeepCopyInto(out *S3Spec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Spec.
func (in *S3Spec) DeepCopy() *S3Spec {
	if in == nil {
		return nil
	}
	out := new(S3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceTargetModeSpec) DeepCopyInto(out *SourceTargetModeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceTargetModeSpec.
func (in *SourceTargetModeSpec) DeepCopy() *SourceTargetModeSpec {
	if in == nil {
		return nil
	}
	out := new(SourceTargetModeSpec)
	in.DeepCopyInto(out)
	return out
}
