# This rule is not used by the project mysqlrestore itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the dbrestore.local.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mysqlrestore
    app.kubernetes.io/managed-by: kustomize
  name: mysqlrestore-editor-role
rules:
- apiGroups:
  - dbrestore.local.com
  resources:
  - mysqlrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbrestore.local.com
  resources:
  - mysqlrestores/status
  verbs:
  - get
