---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - dbrestore.local.com
  resources:
  - mysqlrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbrestore.local.com
  resources:
  - mysqlrestores/finalizers
  verbs:
  - update
- apiGroups:
  - dbrestore.local.com
  resources:
  - mysqlrestores/status
  verbs:
  - get
  - patch
  - update
