apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: job2
  namespace: default
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: job1
        resources: {}
      restartPolicy: Never
status: {}
