apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysqltest
  name: mysqltest
spec:
  containers:
  - image: mysql:latest
    imagePullPolicy: IfNotPresent
    name: mysqltest
    resources: {}
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: qweQWE123
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mysqltest
  name: mysqltest
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysqltest
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
data:
  "mysqlCredential": dXNlcjogcm9vdApwYXNzd2Q6IHF3ZVFXRTEyMwpob3N0OiBteXNxbHRlc3QKcG9ydDogMzMwNgpkYjogdGVzdERCCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: s1
#---
#apiVersion: batch/v1
#kind: Job
#metadata:
#  creationTimestamp: null
#  name: sqldump
#spec:
#  template:
#    metadata:
#      creationTimestamp: null
#    spec:
#      containers:
#      - image: swr.cn-north-4.myhuaweicloud.com/shanwen_img/sqldump:oracel9v1
#        imagePullPolicy: IfNotPresent
#        name: sqldump
#        resources: {}
#        volumeMounts:
#        - name: s1
#          mountPath: /sqlCredential
#          readOnly: true
#      dnsPolicy: ClusterFirst
#      restartPolicy: OnFailure
#      volumes:
#      - name: s1
#        secret:
#          secretName: s1
#status: {}
