apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: destmysqltest
  name: destmysqltest
spec:
  containers:
  - image: mysql:latest
    imagePullPolicy: IfNotPresent
    name: destmysqltest
    resources: {}
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: qweQWE123
    #lifecycle:
    #  postStart:
    #    exec:
    #      command: 
    #      - bash
    #      - -x
    #      - "mysql -uroot -pqweQWE123 -h127.0.0.1 -e 'create database test1'"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: destmysqltest
  name: destmysqltest
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: destmysqltest
  type: NodePort
status:
  loadBalancer: {}
---
